version: '3.4'

services:
  rest:
    #Uncomment line below if you want to build from Github source code
    #Otherwise it will pull pre-built images from Docker Hub
    build: ./rest
    container_name: rest
    image: kjtully/dockersampleapp/sample-app-rest
    environment:
      CONTROLLER_URL: "$CONTROLLER_URL"
      CONTROLLER_PORT: "$CONTROLLER_PORT"
      CONTROLLER_ACCOUNT_NAME: "$CONTROLLER_ACCOUNT_NAME"
      CONTROLLER_ACCESS_KEY: "$CONTROLLER_ACCESS_KEY"
      PORTAL_USERNAME: "$PORTAL_USERNAME"
      PORTAL_PASSWORD: "$PORTAL_PASSWORD"
      AGENT_VERSION: "$AGENT_VERSION"
    ports:
      - "8080:8080"

  db:
    container_name: db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secretquery
    ports:
      - "3306:3306"

  web:
    #Uncomment line below if you want to build from Github source code
    #Otherwise it will pull pre-built images from Docker Hub
    build: ./web
    container_name: web
    image: kjtully/dockersampleapp/sample-app-web
    environment:
      APPDYNAMICS_CONTROLLER_HOST_NAME: "$APPDYNAMICS_CONTROLLER_HOST_NAME"
      APPDYNAMICS_CONTROLLER_PORT: "$APPDYNAMICS_CONTROLLER_PORT"
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: "$APPDYNAMICS_CONTROLLER_SSL_ENABLED"
      APPDYNAMICS_AGENT_ACCOUNT_NAME: "$APPDYNAMICS_AGENT_ACCOUNT_NAME"
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "$APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY"
      APPDYNAMICS_AGENT_APPLICATION_NAME: "$APPDYNAMICS_AGENT_APPLICATION_NAME"
      APPDYNAMICS_AGENT_TIER_NAME: "$APPDYNAMICS_AGENT_TIER_NAME"
      APPDYNAMICS_AGENT_NODE_NAME: "$APPDYNAMICS_AGENT_NODE_NAME"
      APP_ID:
    ports:
      - "3000:3000"
