version: '2'

services:
  rest:
    #Uncomment line below if you want to build from Github source code
    #Otherwise it will pull pre-built images from Docker Hub
    #build: ./rest
    container_name: rest
    image: kjtully/dockersampleapp/sample-app-rest
    environment:
      - CONTROLLER_URL=
      - CONTROLLER_PORT=
      - CONTROLLER_ACCOUNT_NAME=
      - CONTROLLER_ACCESS_KEY=
      - PORTAL_USERNAME=
      - PORTAL_PASSWORD=
      - AGENT_VERSION=
    links:
      - db
    ports:
      - "8080:8080"

  db:
    container_name: db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secretquery
    ports:
      - "3306:3306"

  web:
    #Uncomment line below if you want to build from Github source code
    #Otherwise it will pull pre-built images from Docker Hub
    #build: ./web
    container_name: web
    image: kjtully/dockersampleapp/sample-app-web
    environment:
      - CONTROLLER_URL=
      - CONTROLLER_PORT=
      - CONTROLLER_ACCOUNT_NAME=
      - CONTROLLER_ACCESS_KEY=
      - APP_ID=
    links:
      - rest
      - db
    ports:
      - "3000:3000"
